apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-config
  namespace: ecommerce
data:
  SPRING_PROFILES_ACTIVE: "kubernetes"
  SPRING_R2DBC_URL: "r2dbc:mysql://mysql-service:3306/ecommerce"
  SPRING_FLYWAY_URL: "jdbc:mysql://mysql-service:3306/ecommerce"
  SPRING_DATA_REDIS_HOST: "redis-service"
  SPRING_DATA_REDIS_PORT: "6379"
