apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ecommerce

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - mysql.yaml
  - redis.yaml
  - app.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: ecommerce
