apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secret
  namespace: ecommerce
type: Opaque
stringData:
  SPRING_R2DBC_USERNAME: "root"
  SPRING_R2DBC_PASSWORD: "password"
  SPRING_FLYWAY_USER: "root"
  SPRING_FLYWAY_PASSWORD: "password"
  JWT_SECRET: "your-256-bit-secret-key-for-jwt-token-generation"
  MYSQL_ROOT_PASSWORD: "password"
